### ISSUE TITLE
세션 완료 후 리소스 제거에 대한 언급 추가를 요청합니다

### ISSUE THREAD

**Issue by roeniss** [seohyun0120/amathon-eb-circleci#2]
세션 진행에 사용된 리소스의 뒷정리에 대한 언급을 추가해주셨으면 좋겠습니다.

- Circle CI 에서 "Stop building" 눌러서 연동 종료
- 새로 만들었던 Iam Role 삭제
- Elastic Beanstalk 리소스 전체 삭제

제가 생각한 것은 이 정도입니다.

**Comment by seohyun0120** [comment]
네! 삭제가이드 추가하겠습니다. 감사합니다

**Comment by seohyun0120** [comment]
삭제가이드 추가하여 issue close합니다 :)
