### ISSUE TITLE
[nodemon] Internal watch failed: watch ENOSPC

### ISSUE THREAD

**Issue by Dailyscat** [seohyun0120/amathon-eb-circleci#6]
환경:
npm 5.4.2
linux 18.04

해결:
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

참조:
`https://github.com/remy/nodemon/issues/907`

**Comment by seohyun0120** [comment]
가이드에 해당 이슈 추가해두었습니다 :)
